config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/post/:id', to: 'admin#show_post', as: 'admin_post'
  end
  get 'search', to: 'search#index'

  devise_for :users,controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :after_signup

  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5, maximum: 50 }
    validates :body, presence: true, length: { minimum: 10, maximum: 1000 }
  end
  

app/models/project.rb
class Project < ApplicationRecord
    has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy

  has_one_attached :avatar
  has_one :address, dependent: :destroy, inverse_of: :user, autosave: true
  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  # Class level accessor http://apidock.com/rails/Class/cattr_accessor
  cattr_accessor :form_steps do
    %w[sign_up set_name set_address find_users]
  end

  # Instance level accessor http://apidock.com/ruby/Module/attr_accessor
  attr_accessor :form_step

  def form_step
    @form_step ||= 'sign_up'
  end

  with_options if: -> { required_for_step?('set_name') } do |step|
    step.validates :first_name, presence: true
    step.validates :last_name, presence: true
  end

  validates_associated :address, if: -> { required_for_step?('set_address') }

    def full_name
      "#{first_name.capitalize unless first_name.nil?} #{last_name.capitalize unless last_name.nil?}"
    end

    accepts_nested_attributes_for :address, allow_destroy: true

    def required_for_step?(step)
      # All fields are required if no form step is present
      form_step.nil?
  
      # All fields from previous steps are required if the
      # step parameter appears before or we are on the current step
      form_steps.index(step.to_s) <= form_steps.index(form_step.to_s)
    end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index; end


  def posts
    @posts = Post.all.includes(:user)
  end


  def comments; end

  def users
    @users = User.all
    end


  def show_post
    @post = Post.includes(:user, comments: [:user, :rich_text_body]).find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
  <p>
    <%= link_to "Admin", admin_path %><%= " > #{params[:action].capitalize}" unless params[:action].eql?("index") %>
  </p>
  <div class="btn-group">
    <%= render "admin/link", resource: Post %>
    <%= render "admin/link", resource: User %>
  </div>
</div>

app/views/admin/comments.html.erb
<div class="container">
  <h1 class="text-center">Adminstrator</h1>
  <%= render 'admin/nav_links' %>
</div>

app/views/admin/index.html.erb
<div class="container">
  <h1 class="text-center">Adminstrator</h1>
  <%= render 'admin/nav_links' %>
</div>

app/views/admin/posts.html.erb
<div class="container">
  <h1 class="text-center">Adminstrator</h1>
  <%= render 'admin/nav_links' %>
  <table class="table table-light table-striped border">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Post</th>
        <th scope="col">Author</th>
        <th scope="col">Comments</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <th scope="row"><%= post.id %></th>
          <td><%= link_to post.title.truncate(15), admin_post_path(post) %></td>
          <td><%= post.user.full_name %></td>
          <td><%= pluralize(post.comments.size, "Comment") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/show_post.html.erb
<div class="container">
  <h1 class="text-center">Administrator</h1>
  <%= render "admin/nav_links" %>
  <div class="text-center mt-5">
    <div class="btn-group">
      <%= link_to "Edit", edit_post_path(@post), class:"btn btn-warning m-1" %>
      <%= button_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger m-1" %>
    </div>
  </div>
  <div class="row mt-1">
    <p>
      <strong>Title:</strong> <%= @post.title %>
    </p>
  </div>
  <div class="row mt-1">
    <p>
      <strong>Views:</strong> <%= @post.views %>
    </p>
  </div>
  <div class="row mt-1">
    <p><strong>Author:</strong>
      <%= "#{@post.user.email} | #{@post.user.full_name} | #{pluralize(@post.user.views, "View")}" %>
    </p>
  </div>
  <div class="row mt-1">
    <strong>Body:</strong> <%= @post.body %>
  </div>
  <div class="row mt-1">
    <strong><%= pluralize(@post.comments.count, "Comment") %>:</strong>
    <% @post.comments.each do |comment| %>
      <div class="row mt-1">
        <%= comment.user.full_name %>
        <%= comment.body %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users.html.erb
<div class="container">
  <h1 class="text-center">Adminstrator</h1>
  <%= render 'admin/nav_links' %>
  <table class="table table-light table-striped border">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">user</th>
         <th scope="col">email</th>

      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          <td><%= user.full_name %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>